worker_processes 1;
worker_rlimit_nofile 1024;

events {
    worker_connections 256;
    multi_accept on;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    tcp_nopush      on;
    tcp_nodelay     on;

    keepalive_timeout 35;
    keepalive_requests 100;

    client_max_body_size 10m;
    client_body_timeout 30;
    client_header_timeout 10;
    send_timeout 30;

    gzip on;
    gzip_min_length 1024;
    gzip_comp_level 2;
    gzip_types text/plain text/css application/javascript application/json image/svg+xml;
    gzip_vary on;

    open_file_cache max=500 inactive=30s;
    open_file_cache_valid 60s;
    open_file_cache_min_uses 2;

    server_tokens off;

    server {
        listen 80;
        server_name _;

        root /usr/share/nginx/html;
        index index.html;

        location = /health {
            access_log off;
            return 200 "ok\n";
            add_header Content-Type text/plain;
        }



        location / {
            try_files $uri $uri/ /index.html;
        }
    }
}
